import { Role } from "../entities/user/role";

// permission.enum.ts
export enum Permission {
  // Absence-Request
  CAN_GET_ABSENCE_REQUEST = 'CAN_GET_ABSENCE_REQUEST',
  CAN_POST_ABSENCE_REQUEST = 'CAN_POST_ABSENCE_REQUEST',
  CAN_PATCH_ABSENCE_REQUEST = 'CAN_PATCH_ABSENCE_REQUEST',
  CAN_DELETE_ABSENCE_REQUEST = 'CAN_DELETE_ABSENCE_REQUEST',
  CAN_APPROVE_ABSENCE_REQUEST = 'CAN_APPROVE_ABSENCE_REQUEST',
  CAN_REJECT_ABSENCE_REQUEST = 'CAN_REJECT_ABSENCE_REQUEST',

  // EmployeeWtr
  CAN_GET_EMPLOYEE_WTR = 'CAN_GET_EMPLOYEE_WTR',
  CAN_POST_EMPLOYEE_WTR = 'CAN_POST_EMPLOYEE_WTR',
  CAN_PATCH_EMPLOYEE_WTR = 'CAN_PATCH_EMPLOYEE_WTR',
  CAN_DELETE_EMPLOYEE_WTR = 'CAN_DELETE_EMPLOYEE_WTR',

  // PublicHolidays
  CAN_GET_PUBLIC_HOLIDAYS = 'CAN_GET_PUBLIC_HOLIDAYS',
  CAN_PATCH_PUBLIC_HOLIDAYS = 'CAN_PATCH_PUBLIC_HOLIDAYS',

  // Path for Route (don't forget to add it on app.routes.ts)
  CAN_ROUTE_TO_POST_ABSENCE_REQUEST = 'CAN_ROUTE_TO_POST_ABSENCE_REQUEST',
}

export const ALLOWED_PERMISSIONS: Record<Role, string[]> = {
  [Role.EMPLOYEE]: [
    Permission.CAN_GET_ABSENCE_REQUEST,
    Permission.CAN_POST_ABSENCE_REQUEST,
    Permission.CAN_ROUTE_TO_POST_ABSENCE_REQUEST,
    Permission.CAN_PATCH_ABSENCE_REQUEST,
    Permission.CAN_DELETE_ABSENCE_REQUEST,
    Permission.CAN_GET_EMPLOYEE_WTR,
    Permission.CAN_GET_PUBLIC_HOLIDAYS,
  ],
  [Role.ADMINISTRATOR]: [
    Permission.CAN_GET_ABSENCE_REQUEST,
    Permission.CAN_POST_ABSENCE_REQUEST,
    Permission.CAN_ROUTE_TO_POST_ABSENCE_REQUEST,
    Permission.CAN_PATCH_ABSENCE_REQUEST,
    Permission.CAN_DELETE_ABSENCE_REQUEST,
    Permission.CAN_GET_EMPLOYEE_WTR,
    Permission.CAN_POST_EMPLOYEE_WTR,
    Permission.CAN_PATCH_EMPLOYEE_WTR,
    Permission.CAN_DELETE_EMPLOYEE_WTR,
    Permission.CAN_GET_PUBLIC_HOLIDAYS,
    Permission.CAN_PATCH_PUBLIC_HOLIDAYS,
  ],
  [Role.MANAGER]: [
    Permission.CAN_GET_ABSENCE_REQUEST,
    Permission.CAN_POST_ABSENCE_REQUEST,
    Permission.CAN_ROUTE_TO_POST_ABSENCE_REQUEST,
    Permission.CAN_PATCH_ABSENCE_REQUEST,
    Permission.CAN_DELETE_ABSENCE_REQUEST,
    Permission.CAN_GET_EMPLOYEE_WTR,
    Permission.CAN_GET_PUBLIC_HOLIDAYS,
    Permission.CAN_APPROVE_ABSENCE_REQUEST,
    Permission.CAN_REJECT_ABSENCE_REQUEST,
  ],
};